In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score


In [25]:
path = '../../data/data자료/Advertising.csv'
ad = pd.read_csv(path, index_col=0)

In [26]:
#pcr 모델 적용 

# 독립변수(x), 종속변수(y) 분리 

ad.shape

(200, 4)

In [27]:
x = ad.iloc[:, :-1] # tv, newspapers, radio
y = ad.iloc[:, -1:] # sales

In [28]:
x.shape

(200, 3)

In [29]:
y.shape

(200, 1)

In [30]:
pca = PCA(n_components=2) # 변수 3개를 2개로 

In [31]:
pca.fit(x)

PCA(n_components=2)

In [32]:
pca.explained_variance_ratio_
# 2개 변수 >> 97%

array([0.91415577, 0.06398422])

In [33]:
#pc_score
z = pca.fit_transform(x) # pca로 변환된 데이터

In [34]:
z #스탠다드 스케일링한 값 

array([[ 8.37885459e+01,  3.97809922e+01],
       [-1.02138730e+02,  2.11666084e+01],
       [-1.28992484e+02,  4.66162737e+01],
       [ 5.07097169e+00,  3.24605596e+01],
       [ 3.40590034e+01,  2.09381554e+01],
       [-1.37372550e+02,  5.31645709e+01],
       [-8.95411919e+01, -1.56105218e+00],
       [-2.71687122e+01, -1.85233852e+01],
       [-1.39089396e+02, -3.26587125e+01],
       [ 5.23964374e+01, -1.70725851e+01],
       [-8.12021689e+01, -1.07115904e+01],
       [ 6.72413078e+01, -2.57554904e+01],
       [-1.22554515e+02,  3.94626040e+01],
       [-5.00532789e+01, -2.65102072e+01],
       [ 5.73839300e+01,  1.68358060e+01],
       [ 4.89406812e+01,  2.87251422e+01],
       [-7.78006550e+01,  8.41188799e+01],
       [ 1.34889902e+02,  2.69844146e+01],
       [-7.80470423e+01, -1.10237502e+01],
       [ 8.60991305e-02, -1.04730127e+01],
       [ 7.17442417e+01,  2.16291631e+01],
       [ 9.00507477e+01, -1.47109210e+01],
       [-1.33597890e+02,  1.75720041e+01],
       [ 8.

In [39]:
# PCA 한 후 scaled 된 값 활용 z
# >> 훈련용 데이터, 테스트 데이터 구분 

from sklearn.model_selection import train_test_split

#pca로 변환된 데이터로 구분
z_train, z_test, y_train, y_test = \
train_test_split(z, y, test_size=0.2, random_state=42)

In [40]:
z_train[:4]

array([[ -31.3087204 ,  -11.96150355],
       [  29.43777398,  -28.08635036],
       [-103.81982916,    7.35123207],
       [ -85.02497438,  -13.72222433]])

In [41]:
z_train.shape, z_test.shape, y_train.shape, y_test.shape

((160, 2), (40, 2), (160, 1), (40, 1))

In [42]:
#선형회귀 객체 생성 
lr = linear_model.LinearRegression()

lr.fit(z_train, y_train)

LinearRegression()

In [43]:
#예측

#1. training data 활용, 예측 
z_train_pred = lr.predict(z_train)
#2. test data 활용 ,예측(**)
z_test_pred = lr.predict(z_test)


In [45]:
z_train_pred[:5]

array([[11.60873346],
       [13.23498023],
       [ 9.67257788],
       [ 8.9286559 ],
       [15.87267065]])

In [47]:
y_train[:5]

Sales
80    11.0
198   12.8
39    10.1
25     9.7
123   11.6

In [58]:
z_test_pred[:5]

array([[16.6347724 ],
       [18.56325639],
       [21.78653861],
       [ 9.25608939],
       [16.1090779 ]])

In [59]:
y_test[:5]

Sales
96    16.9
16    22.4
31    21.4
159    7.3
129   24.7

In [50]:
#coef_ 

print('coefficients:', lr.coef_) #가중치

coefficients: [[0.04735184 0.07753322]]


In [52]:
#training data MSE 
print('Training data MSE:%.3f' %mean_squared_error(y_train, z_train_pred))

Training data MSE:7.746


In [53]:
#test data MSE (**)
print('Test data MSE:%.3f' %mean_squared_error(y_test, z_test_pred))

Test data MSE:10.560


In [57]:
#결정계수 
print("r2 score: %.3f" %r2_score(y_train, z_train_pred))
print("r2 score: %.3f" %r2_score(y_test, z_test_pred))

r2 score: 0.701
r2 score: 0.665
