In [2]:
import pandas as pd 
import numpy as np 


from sklearn import linear_model
from sklearn.metrics import mean_squared_error

from sklearn.model_selection import KFold

Ridge regression (릿지 회귀)
- 알파값이 클수록 계수가 줄어듬 0에 가깝게

In [17]:

reg = linear_model.Ridge(alpha=0.5) #alpha : tuning parameter (lambda 상수)



In [18]:
#훈련 
reg.fit([[0,0],[0,0],[1,1]], [0,.1,1])
#x = [[0,0],[0,0],[1,1]]
#y = [0,.1,1]

Ridge(alpha=0.5)

In [19]:
pred_test = reg.predict([[0,1]])

In [20]:
pred_test

array([0.48181818])

In [21]:
reg.coef_

array([0.34545455, 0.34545455])

Lasso 간단예제
- 알파가 크면 안 닿는 변수들을 0으로 바꿈 (변수 추출 효과 있음)

In [27]:
# reg = linear_model.Lasso(alpha=0.1)
reg = linear_model.Lasso(alpha=1.0)

reg.fit([[0, 0], [1, 1]], [0, 1]) 

Lasso()

In [28]:
pred_test = reg.predict([[0, 1]]) 
pred_test

array([0.5])

In [30]:
reg.coef_ # 0으로 만듬

array([0., 0.])

Advertising 데이터 활용 모델 선택 

In [33]:
ad = pd.read_csv('../../data/data자료/Advertising.csv', index_col=0)
ad.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [37]:
#ad 데이터에 Lasso 적용 (최적읜 lambda 선정)

n_fold = 5
 

for t_param in (0.001, 0.1, 1): #lambda값 설정 
    print("Lambda:", t_param)
    kf = KFold(n_splits=n_fold)
    idx = 1
    
    sum_val_mse = 0
    for train, val in kf.split(ad):
        print('KFold:', idx)
        
        #training set의 feature와 response 분리
        train_x = ad.iloc[train][['TV','Radio','Newspaper']]
        train_y = ad.iloc[train][['Sales']]
        
        #validation set의 feature와 response 분리
        val_x = ad.iloc[val][['TV','Radio','Newspaper']]
        val_y = ad.iloc[val][['Sales']]
        
        #Lasso 적용 
        regr = linear_model.Lasso(alpha=t_param)
        
        #훈련 
        regr.fit(train_x[['TV','Radio','Newspaper']], train_y)
        
        #coef_
        print("Coefficients: ", regr.coef_)
        
        #validation set 예측
        val_y_pred = regr.predict(val_x[['TV','Radio','Newspaper']])
        
        #validation MSE 
        val_mse = mean_squared_error(val_y, val_y_pred)
        
        sum_val_mse = val_mse
        
        print("--" *100)
        idx += 1 
    print("Average Validation MSE: %.3f" %(sum_val_mse / n_fold))
    print("**" * 100 )
        
        
        

Lambda: 0.001
KFold: 1
Coefficients:  [0.04585753 0.18790125 0.00361145]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
KFold: 2
Coefficients:  [0.04513111 0.1879391  0.00140999]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
KFold: 3
Coefficients:  [ 0.04698029  0.18872464 -0.00235756]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
KFold: 4
Coefficients:  [ 0.04315907  0.20013028 -0.00758214]
---------------------------------------------------------------------------------------------------------------------------------------------