In [1]:
import numpy as np 

#1차원
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [2]:
#2차원 
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
data[1]

array([3, 4])

In [4]:
#특정값 뽑을때 
data[0,1] #0번째 리스트에 1번째 값

2

In [5]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [6]:
#0으로 채워진 array 
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [9]:
#차원 (dim)
array_example.ndim

3

In [10]:
#크기 (size)
array_example.size

24

In [11]:
#모양(shape) 
array_example.shape # (2,4) 가 3개 

(3, 2, 4)

In [12]:
#array 모양 바꾸기 

# 1차원 배열  
data = np.array([1,2,3,4,5,6])
data

array([1, 2, 3, 4, 5, 6])

In [16]:
#2차원 배열 (reshape)
print(data.reshape(2,3))
print()
print(data.reshape(3,2))


[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [17]:
data = data.reshape(3,2)
data.T #transpose 전치 (행열 변환)

array([[1, 3, 5],
       [2, 4, 6]])

In [19]:
#기본연산 (같은 구조여야함)
ones_row = np.array([[1,1]])
data = np.array([1,2,3,4,5,6])

# 더하기 
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [22]:
data.max() #최대값
data.min() #최소값

data.sum() #모든 값의 합 


21

In [24]:
#저장할 데이터 생성

csv_arr = np.array([[1,2,3,4],[5,6,7,8]])

In [25]:
#np로 파일 저장
np.savetxt('../../data/data자료/new_file.csv', csv_arr)

In [26]:
#np로 파일 불러오기 
np.loadtxt('../../data/data자료/new_file.csv')

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])